### ISSUE TITLE
General Data Protection Regulation tips

### ISSUE THREAD

**Issue by TimDeJ** [statamic/docs#148]
It would be nice to have some pointers how to correctly setup Statamic in line with the General Data Protection Regulation or simular regulations. Especially where it comes to user accounts. While storing in file has is the prefered way for usabilty, it is also the hardes to use in line with the GDPR and especially with the "Right to be forgotten" which makes it impossible to add users to a version control repository as removing a single user from the complete repository is pretty much impossible.

**Comment by jasonvarga** [comment]
You're free to _not_ version your user files. Then once they're deleted, they're deleted.

If you do version them, this makes it complicated as you pointed out, since they're in the Git history.

I'm definitely not an expert on GDPR so do your own research, talk to your lawyers, etc. But, it looks like you could consider Git a backup, and you explain that to the user. Keep track of deletions somehow so if you ever need to use the backup so you can re-delete the user.

**Comment by TimDeJ** [comment]
In V2 we added all the users to the .gitignore and have a automatic backup of the users files on the server. I assume a simmilar approch would work again. migrating from V2 to V3 keeping the users means testing is a bit harder as we don't accidentally want to put them in the git repository.
