### ISSUE TITLE
Broken link to fieldsets docs

### ISSUE THREAD

**Issue by CasperEngl** [statamic/docs#305]
## Issue

On the page https://statamic.dev/fields#blueprints-amp-fieldsets under "Blueprints & Fieldsets" the link to Fieldsets currently goes 404.

## Suggested change

Change the link from: https://statamic.dev/fieldsets
To this link: https://statamic.dev/fieldtypes/fieldset

## Bonus

[Ohdear.app](https://ohdear.app/) has a broken link crawler. Seeing as the /fieldsets page sends the 404 status code, ohdear can find such links and tell you about them.

**Comment by janparkio** [comment]
I like the suggested change, however, the link: https://statamic.dev/fieldtypes/fieldset feels almost pointless.
Compared to other pages in the Statamic documentation, this one feels very much lacking.

The methodology to use Fieldsets is beautifully simple, but by no means intuitive for a beginner, and it is actually a really great tool, I am surprised nobody changed it yet.

As you can see I've made a similar issue #296 and at the moment is closed. But the issue was not solved.
