### ISSUE TITLE
impossible to create private addon

### ISSUE THREAD

**Issue by miloslavkostir** [statamic/docs#415]
Hi

It's impossible to create addon by this page https://statamic.dev/extending/addons

If I use this in `composer.json`:
```
    "extra": {
        "statamic": {
            "name": "MyAddon",
            "description": "Example addon"
        }
    }
```
I get connection error:
```
> @php artisan statamic:install --ansi

   GuzzleHttp\Exception\ConnectException 

  Connection refused for URI https://statamic.com/api/v1/marketplace/packages/my-vendor/my-addon/dev-master
```
(of course, the URI doesn't exists)

**Comment by duncanmcclean** [comment]
Can you share your whole `composer.json` file please (of the addon)?

**Comment by jesseleite** [comment]
@miloslavkostir A private addon needs to be registered using composer's [repositories](https://getcomposer.org/doc/05-repositories.md#repository), so that you can reference a local file path.

We actually handle this for you, if you `php please make:addon` to scaffold out your addon. ie)

```
php please make:addon jesseleite/my-package
```

That will scaffold out a local/private addon, and will automatically setup your app's composer.json for you. If you ever decide to publish your addon on the marketplace, you can move the code out into it's own public repo, etc.
