### ISSUE TITLE
Extending Bard docs

### ISSUE THREAD

**Issue by robdekort** [statamic/docs#424]
This whole page is unfortunately very unclear to me: https://statamic.dev/extending/bard#extensions

In my opinion it would benefit from the following:

- What is TipTap (in relation to Statamic and Bard)
- What is ProseMirror (in relation to Statamic and Bard)
- What is Mark
- Where do you put this JS Code
- What is ProseMirror rendering
- TipTap library / API?
- Example: simple button that does a simple thing like adding a class or wrapping in stuff in an element
- Less assumed knowledge

**Comment by jelleroorda** [comment]
Well I can see what you mean, to me the docs are clear (I've created a few extensions for Tiptap before, however not for the Bard editor). I think we should mention in the docs that this is quite the complicated topic to extend, since (in my opinion) Tiptap takes quite some time to get started with. Before you even get started you'd be best off reading the [entire prose mirror guide](https://prosemirror.net/docs/guide/). I also have some mixed feelings about Statamic needing to explain the libraries. Like I said I would propose to just mentioning this is pretty complicated stuff, and where to start off reading if you're going to attempt to create something instead. The parts that are specific to Bard do need to be documented, but they are as far as I can see.

**Comment by robdekort** [comment]
I think it's totally fair to note this it's complicated to extend this and requires extensive knowledge of those libraries. And you're totally right about needing to explain the libraries.

But to me it was already very unclear what library is used for what (I still don't tbh ;-)). I don't mind learning stuff, but this doc - without any prior knowledge - raised more questions for me since it assumes you know what is being used where and for what reason. An easy win might also be to explain where each bit of example code should go.

**Comment by jelleroorda** [comment]
Well, fair enough, I'll try to cook something up!
