### ISSUE TITLE
Documentation about scheduling

### ISSUE THREAD

**Issue by rrelmy** [statamic/docs#537]
There seems to exist a please command, which I used naively because of old times sake.

But it does not seem to do anything 😕 
```
php please schedule:run
No scheduled commands are ready to run.
```

while artisan
```
$ php artisan schedule:run
[2021-09-16T14:04:08+00:00] Running scheduled command: 'php' 'artisan' firebase:send > '/dev/null' 2>&1
[2021-09-16T14:04:08+00:00] Running scheduled command: 'php' 'artisan' send:sms > '/dev/null' 2>&1
```

does stuff

I could not find any hints to the laravel docs inside statamic docs.

**Comment by duncanmcclean** [comment]
I wonder if this might actually be a bug instead 🤔  

I would have assumed it would just alias it to the Artisan version of the command. Who knows.

**Comment by jasonvarga** [comment]
Yeah, `please` just aliases the command to `artisan`.

Maybe you're seeing that just because there wasn't anything in the schedule at that moment.

Running `please schedule:run` worked for me.

![image](https://user-images.githubusercontent.com/105211/133630897-1be36e4a-558d-4777-87a4-c68f82f34467.png)

There's nothing in the docs because there's nothing Statamic-specific about it. It's really just a plain Laravel feature.

**Comment by rrelmy** [comment]
Very strange, I can run the schedule command with please and get mostly nothing, but with artisan it always runs certain commands.

We configured the cronjob on the server to run the please version which never triggered the addon commands.

I will investigate further and report a bug if I find something.
