### ISSUE TITLE
Torchlight required?

### ISSUE THREAD

**Issue by jmalko** [statamic/docs#729]
Torchlight is a requirement to see certain pages.  Is this on purpose?

**Comment by jackmcdade** [comment]
What do you mean?

**Comment by jmalko** [comment]
I am writing up some Tips & Tricks PRs.  If you do not have a `TORCHLIGHT_TOKEN` set in your env, I get an error page.

**Comment by jmalko** [comment]
https://flareapp.io/share/17DyRnZ5#F84

**Comment by jackmcdade** [comment]
Ah, that sucks – I didn't realize it would throw an error. You could `composer remove torchlight/torchlight-commonmark` locally and just not commit that change. That should work.

**Comment by jackmcdade** [comment]
Did a little code diving and it looks like if you set the `APP_ENV` to `production` it won't throw the error. Since most people outside our team are just running docs offline or are writing PRs, it's no big deal to leave the default to prod there. So I did. https://github.com/statamic/docs/commit/b6c26928648775770999b619eadf0514a75b1f9b
