### ISSUE TITLE
Storing entries in a Database

### ISSUE THREAD

**Issue by JPAntonisse** [statamic/docs#963]
There is no docs about storing Statamic Data in a database, which is easily doable with the Eloquent Driver. (https://github.com/statamic/eloquent-driver)

Please update your docs to have a (searchable) header and information on the Eloquent Driver.

I had to search quite long for it, so perhaps others won't feel the same pain.

**Comment by joshuablum** [comment]
Hey @JPAntonisse,

Thanks for the feedback!

There are two entries on this topic in the docs:
1. [Storing Entries in a Database](https://statamic.dev/tips/storing-entries-in-a-database)
2. [Storing Users in a Database](https://statamic.dev/tips/storing-users-in-a-database)

And it's also indexed by the docs' search:
<img width="1613" alt="CleanShot 2022-12-07 at 5 31 21@2x" src="https://user-images.githubusercontent.com/3824203/206236044-597c6039-b8e3-433e-bb8e-47479bb0070b.png">

The [README of the Eloquent Driver's repository](https://github.com/statamic/eloquent-driver/blob/master/README.md) also includes all the necessary information on how to use it.

But you're right, the docs in this area could be improved since the Eloquent Driver received a major update recently 👍

**Comment by JPAntonisse** [comment]
[Storing Entries in a Database](https://statamic.dev/tips/storing-entries-in-a-database) Is only talking about storing _Entries_ in the database even when it's possible to relocate all the statamic data in a database with the [Eloquent Driver](https://github.com/statamic/eloquent-driver).

 Which is a very good functionality and it would be unfortunate when left out.
